artifact_uri: /trained_networks/0/a372ed0a321e46a2b87acc4358dad0dd/artifacts
end_time: 1705011147755
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a372ed0a321e46a2b87acc4358dad0dd
run_uuid: a372ed0a321e46a2b87acc4358dad0dd
source_name: ''
source_type: 4
source_version: ''
start_time: 1697588732172
status: 3
tags: []
user_id: YF
